((nil . ((project-name . "FancyGuy Platform Installer Plugin")))
 (php-mode . ((source-path . "src/")
	      (source-namespace . "FancyGuy\\Composer\\Platform")
	      (tests-path . "tests/")
	      (tests-namespace . "FancyGuy\\Composer\\Platform\\Test"))))
